/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
 
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import logica.conexion;
import static presentacion.ListaDeProductos.*;

/**
 *
 * @author boy_d
 */
public class EditarUnProducto extends javax.swing.JFrame {

    conexion c = new conexion();
    Connection con = c.getConexion();
    int FilaSelec = TblListaProductos.getSelectedRow();
    /**
     * Creates new form EditarUnProducto
     */
    public EditarUnProducto() {
              
        initComponents();
        this.setResizable(false);
        
        try {

                idproducto = TblListaProductos.getValueAt(FilaSelec, 0).toString();
                TxtTipo.setText(TblListaProductos.getValueAt(FilaSelec, 1).toString());
                TxtDescripcion.setText(TblListaProductos.getValueAt(FilaSelec, 2).toString());
                TxtMedida.setText(TblListaProductos.getValueAt(FilaSelec, 3).toString());
                TxtMaterial.setText(TblListaProductos.getValueAt(FilaSelec, 4).toString());
                TxtPrecio.setText(TblListaProductos.getValueAt(FilaSelec, 5).toString());
                TxtCantidad.setText(TblListaProductos.getValueAt(FilaSelec, 6).toString());
                LblFecha.setText(TblListaProductos.getValueAt(FilaSelec, 7).toString());



            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error en la consulta Editar: " + e);
            }

             
      ListaDeProductos ListaProductos = new ListaDeProductos();
        ListaProductos.setVisible(false);
        ListaProductos.dispose();  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnModificarProducto = new javax.swing.JButton();
        TxtCantidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtMaterial = new javax.swing.JTextField();
        TxtPrecio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtTipo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtMedida = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BtnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        LblFecha = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtDescripcion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        BtnModificarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/guardar.png"))); // NOI18N
        BtnModificarProducto.setText("Modificar Producto");
        BtnModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarProductoActionPerformed(evt);
            }
        });
        BtnModificarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnModificarProductoKeyPressed(evt);
            }
        });

        TxtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtCantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCantidadKeyTyped(evt);
            }
        });

        jLabel6.setText("Cantidad:");

        TxtMaterial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtMaterialKeyPressed(evt);
            }
        });

        TxtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtPrecioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtPrecioKeyTyped(evt);
            }
        });

        jLabel7.setText("Material:");

        jLabel5.setText("Precio:");

        TxtTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTipoKeyPressed(evt);
            }
        });

        jLabel9.setText("Tipo:");

        TxtMedida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtMedidaKeyPressed(evt);
            }
        });

        jLabel10.setText("Fecha");

        BtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/cancelar.png"))); // NOI18N
        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        BtnCancelar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCancelarKeyPressed(evt);
            }
        });

        jLabel2.setText("Medida:");

        LblFecha.setText("jLabel11");

        jLabel1.setText("Descripcion:");

        TxtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtDescripcionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(TxtMaterial, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jLabel7)
                            .addComponent(TxtMedida)
                            .addComponent(jLabel9)
                            .addComponent(jLabel5)
                            .addComponent(TxtPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(TxtCantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel1)
                            .addComponent(TxtDescripcion)
                            .addComponent(TxtTipo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(BtnCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModificarProducto, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblFecha)
                .addGap(18, 18, 18)
                .addComponent(BtnModificarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarProductoActionPerformed
        // TODO add your handling code here:

        try {
            PreparedStatement ps = con.prepareStatement("UPDATE inventario SET producto='"
                + TxtTipo.getText()+ "',descripcion='" + TxtDescripcion.getText()
                + "',medida='" + TxtMedida.getText()+ "',material='" + TxtMaterial.getText() 
                + "',precio='" + TxtPrecio.getText() + "',cantidad='"+TxtCantidad.getText()
                +"' WHERE id='" + idproducto + "' ");

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Datos Actualizados Correctamente ");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la consulta Modificar: " + e);
        }
        ListaDeProductos ListaProducto = new ListaDeProductos();
        ListaProducto.setLocationRelativeTo(null);
        ListaProducto.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnModificarProductoActionPerformed

    private void BtnModificarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnModificarProductoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnModificarProducto.doClick();
        }
    }//GEN-LAST:event_BtnModificarProductoKeyPressed

    private void TxtCantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCantidadKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnModificarProducto.requestFocus();
            BtnModificarProducto.doClick();
        }
    }//GEN-LAST:event_TxtCantidadKeyPressed

    private void TxtMaterialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMaterialKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            TxtMedida.requestFocus();
        }
    }//GEN-LAST:event_TxtMaterialKeyPressed

    private void TxtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            TxtCantidad.requestFocus();
        }
    }//GEN-LAST:event_TxtPrecioKeyPressed

    private void TxtTipoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTipoKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            TxtDescripcion.requestFocus();
        }
    }//GEN-LAST:event_TxtTipoKeyPressed

    private void TxtMedidaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMedidaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            TxtPrecio.requestFocus();
        }
    }//GEN-LAST:event_TxtMedidaKeyPressed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        ListaDeProductos ListaProducto = new ListaDeProductos();
        ListaProducto.setLocationRelativeTo(null);
        ListaProducto.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnCancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCancelarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnCancelar.doClick();
           
        }
    }//GEN-LAST:event_BtnCancelarKeyPressed

    private void TxtDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDescripcionKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            TxtMaterial.requestFocus();
        }
    }//GEN-LAST:event_TxtDescripcionKeyPressed

    private void TxtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPrecioKeyTyped
            char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtPrecioKeyTyped

    private void TxtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCantidadKeyTyped
            char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtCantidadKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarUnProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarUnProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarUnProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarUnProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarUnProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnModificarProducto;
    private javax.swing.JLabel LblFecha;
    private javax.swing.JTextField TxtCantidad;
    private javax.swing.JTextField TxtDescripcion;
    private javax.swing.JTextField TxtMaterial;
    private javax.swing.JTextField TxtMedida;
    private javax.swing.JTextField TxtPrecio;
    private javax.swing.JTextField TxtTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
