/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
 
import com.sun.glass.events.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.conexion;

/**
 *
 * @author boy_d
 */
public class ListaDeClientes extends javax.swing.JFrame {
    conexion c = new conexion();
    Connection con = c.getConexion();
    DefaultTableModel modelo;
    String titulo[] = {"Codigo", "Nombre", "Telefono","Descuento %"};
    String data[] = new String[4];
      String opcion;
      int registro;
     public static String CodigoCliente,NombreCliente,TelefonoCliente,DescuentoCliente;
    /**
     * Creates new form ListaDeClientes
     */
    public ListaDeClientes() {
        initComponents();
        consutaCliente();
        this.setResizable(false);
    }
 void consutaCliente() {
         registro=0;
        modelo = new DefaultTableModel(null, titulo) {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        TblClientes.setModel(modelo);

        String sql = "select * from cliente";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                data[0] = rs.getString("id");
                data[1] = rs.getString("nombre");
                data[2] = rs.getString("telefono");
                data[3] = rs.getString("descuento");
                
                modelo.addRow(data);
                registro = registro + 1;
            }
          
            TxtRegistro.setText("Encontrados: " + Integer.toString(registro));
        } catch (Exception e) {
            System.out.println("Error de consulta: " + e.getMessage());
        }
        
     }
     void limpiar(){
     TxtCodigo.setText("");
     TxtNombre.setText("");
     TxtTelefono.setText("");
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblClientes = new javax.swing.JTable();
        BtnRegresar = new javax.swing.JButton();
        TxtRegistro = new javax.swing.JLabel();
        BtnAgregarNuevoCliente = new javax.swing.JButton();
        TxtCodigo = new javax.swing.JLabel();
        BtnEditarCliente = new javax.swing.JButton();
        BtnEliminarCliente = new javax.swing.JButton();
        BtnModificarCliente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtDescuento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        TxtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombreKeyPressed(evt);
            }
        });

        jLabel3.setText("Telefono Del Cliente:");

        TxtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtTelefonoKeyTyped(evt);
            }
        });

        TblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TblClientes);

        BtnRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/regresar-flecha-curva.png"))); // NOI18N
        BtnRegresar.setText("Regresar");
        BtnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegresarActionPerformed(evt);
            }
        });
        BtnRegresar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnRegresarKeyPressed(evt);
            }
        });

        TxtRegistro.setText("jLabel4");

        BtnAgregarNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/boton-redondo-agregar.png"))); // NOI18N
        BtnAgregarNuevoCliente.setText("Agregar Nuevo Cliente");
        BtnAgregarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarNuevoClienteActionPerformed(evt);
            }
        });
        BtnAgregarNuevoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAgregarNuevoClienteKeyPressed(evt);
            }
        });

        BtnEditarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/editar.png"))); // NOI18N
        BtnEditarCliente.setText("Editar Cliente");
        BtnEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarClienteActionPerformed(evt);
            }
        });
        BtnEditarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEditarClienteKeyPressed(evt);
            }
        });

        BtnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/boton-eliminar.png"))); // NOI18N
        BtnEliminarCliente.setText("Eliminar Cliente");
        BtnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarClienteActionPerformed(evt);
            }
        });
        BtnEliminarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnEliminarClienteKeyPressed(evt);
            }
        });

        BtnModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/guardar.png"))); // NOI18N
        BtnModificarCliente.setText("Modificar Cliente");
        BtnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModificarClienteActionPerformed(evt);
            }
        });
        BtnModificarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnModificarClienteKeyPressed(evt);
            }
        });

        jLabel1.setText("Codigo del Cliente:");

        jLabel2.setText("Nombre del Cliente:");

        jLabel4.setText("Descuento Del Cliente:");

        TxtDescuento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDescuentoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnAgregarNuevoCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEditarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnEliminarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnModificarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(TxtNombre)
                    .addComponent(jLabel3)
                    .addComponent(TxtTelefono)
                    .addComponent(BtnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TxtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(TxtDescuento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAgregarNuevoCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEliminarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEditarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addGap(5, 5, 5)
                        .addComponent(TxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnModificarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnRegresar)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            TxtTelefono.requestFocus();

        }
    }//GEN-LAST:event_TxtNombreKeyPressed

    private void TxtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnModificarCliente.requestFocus();

        }
    }//GEN-LAST:event_TxtTelefonoKeyPressed

    private void BtnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegresarActionPerformed
        // TODO add your handling code here:
        Principal ventaPrincipal= new Principal();
        ventaPrincipal.setLocationRelativeTo(null);
        ventaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnRegresarActionPerformed

    private void BtnRegresarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnRegresarKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            BtnRegresar.doClick();
        }
    }//GEN-LAST:event_BtnRegresarKeyPressed

    private void BtnAgregarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarNuevoClienteActionPerformed
        // TODO add your handling code here:

        AgregarUnCliente AgregarCliente= new AgregarUnCliente();
        AgregarCliente.setLocationRelativeTo(null);
        AgregarCliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnAgregarNuevoClienteActionPerformed

    private void BtnAgregarNuevoClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAgregarNuevoClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            BtnAgregarNuevoCliente.doClick();
        }
    }//GEN-LAST:event_BtnAgregarNuevoClienteKeyPressed

    private void BtnEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarClienteActionPerformed
        // TODO add your handling code here:
        int FilaSelec = TblClientes.getSelectedRow();

        if (FilaSelec >= 0) {
            
           
                CodigoCliente=TblClientes.getValueAt(FilaSelec, 0).toString();
                NombreCliente=TblClientes.getValueAt(FilaSelec, 1).toString();
               TelefonoCliente=TblClientes.getValueAt(FilaSelec, 2).toString();
                DescuentoCliente=TblClientes.getValueAt(FilaSelec, 3).toString();
                
                VerificarAdminClientes VerificarAdminCliente= new VerificarAdminClientes (this,true);
        VerificarAdminCliente.setLocationRelativeTo(null);
        VerificarAdminCliente.setVisible(true);  
        this.setVisible(false);
            

        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un Cliente");
        }

    }//GEN-LAST:event_BtnEditarClienteActionPerformed

    private void BtnEditarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEditarClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            TxtNombre.requestFocus();
            BtnEditarCliente.doClick();
        }
    }//GEN-LAST:event_BtnEditarClienteKeyPressed

    private void BtnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarClienteActionPerformed
        // TODO add your handling code here:
        int FilaSelec = TblClientes.getSelectedRow();

        if (FilaSelec >= 0) {
            String Valor = TblClientes.getValueAt(FilaSelec, 0).toString();
            String sql = "DELETE FROM cliente WHERE id='" + Valor + "'";
            try {
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "El Cliente Se Elimino Correctamente");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error en la consulta eliminar: " + e);
            }

        }else{
            JOptionPane.showMessageDialog(this,"Selecione un cliente a eliminar.");
        }
        consutaCliente();
    }//GEN-LAST:event_BtnEliminarClienteActionPerformed

    private void BtnEliminarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnEliminarClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){

            BtnEliminarCliente.doClick();
        }
    }//GEN-LAST:event_BtnEliminarClienteKeyPressed

    private void BtnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarClienteActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement ps = con.prepareStatement("UPDATE cliente SET nombre='"+ TxtNombre.getText()
                + "',telefono='" + TxtTelefono.getText() + "',descuento='" + TxtDescuento.getText()
                + "' WHERE id='" + TxtCodigo.getText() + "' ");

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Datos Actualizados Correctamente ");
            consutaCliente();
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error en la consulta Modificar: " + e);
        }
    }//GEN-LAST:event_BtnModificarClienteActionPerformed

    private void BtnModificarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnModificarClienteKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            BtnModificarCliente.doClick();
        }
    }//GEN-LAST:event_BtnModificarClienteKeyPressed

    private void TxtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtTelefonoKeyTyped
           char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtTelefonoKeyTyped

    private void TxtDescuentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDescuentoKeyTyped
            char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car > '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_TxtDescuentoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaDeClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarNuevoCliente;
    private javax.swing.JButton BtnEditarCliente;
    private javax.swing.JButton BtnEliminarCliente;
    private javax.swing.JButton BtnModificarCliente;
    private javax.swing.JButton BtnRegresar;
    public static javax.swing.JTable TblClientes;
    public static javax.swing.JLabel TxtCodigo;
    public static javax.swing.JTextField TxtDescuento;
    public static javax.swing.JTextField TxtNombre;
    private javax.swing.JLabel TxtRegistro;
    public static javax.swing.JTextField TxtTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
