/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
 
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.conexion;

/**
 *
 * @author boy_d
 */
public final class ListaDeProductos extends javax.swing.JFrame {

    DefaultTableModel modelo;
    conexion c = new conexion();
    Connection con = c.getConexion();
    String titulo[] = {"Codigo", "Tipo", "Descripcion", "Medida", "Material", "Precio", "Cantidad", "Fecha"};
    
    String data[] = new String[8];

        public static String idproducto;

    /**
     * Creates new form ListaDeProductos
     */
    public ListaDeProductos() {
        initComponents();
        this.setResizable(false);
        consutaProducto();
    }

    void consutaProducto() {
    //    TblListaProductos.setDefaultRenderer(Object.class, new ImageesTabla());
        modelo = new DefaultTableModel(null, titulo){
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        

        String sql = "select * from inventario";
        try {
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                data[0] = rs.getString("id");
                data[1] = rs.getString("producto");
                data[2] = rs.getString("descripcion");
                data[3] = rs.getString("medida");
                data[4] = rs.getString("material");
                data[5] = rs.getString("precio");
                data[6] = rs.getString("cantidad");
                data[7] = rs.getString("fechaRegistro");

                modelo.addRow(data);
                TblListaProductos.setModel(modelo);

            }

        } catch (SQLException e) {
            System.out.println("Error de consulta: " + e.getMessage());
        }

    }
    
    void EliminarProducto(){
    int FilaSelec = TblListaProductos.getSelectedRow();
       
        if (FilaSelec >= 0) {
             String Valor = TblListaProductos.getValueAt(FilaSelec, 0).toString();
             String sql = "DELETE FROM inventario WHERE id='" + Valor + "'";
            try {
                Statement st = con.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(this, "El Producto Se Elimino Correctamente");
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(this, "Error en la consulta eliminar: " + e);
            }

        }else{
        JOptionPane.showMessageDialog(this, "Seleccione Un Producto");
        }
        consutaProducto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TblListaProductos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        TblListaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblListaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblListaProductosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblListaProductos);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/boton-redondo-agregar.png"))); // NOI18N
        jMenu1.setText("Agregar Producto");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/boton-eliminar.png"))); // NOI18N
        jMenu2.setText("Eliminar Producto");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/editar.png"))); // NOI18N
        jMenu3.setText("Editar Producto");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/regresar-flecha-curva.png"))); // NOI18N
        jMenu4.setText("Regresar");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        AgregarProducto Agregar = new AgregarProducto();
        Agregar.setLocationRelativeTo(null);
        Agregar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        Principal ListaProducto = new Principal();
        ListaProducto.setLocationRelativeTo(null);
        ListaProducto.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        EliminarProducto();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        int FilaSelec = TblListaProductos.getSelectedRow();
        
        if(FilaSelec != -1){
            idproducto = TblListaProductos.getValueAt(FilaSelec, 0).toString();
            VerificarAdmiProductos VerificarAdminProductos= new VerificarAdmiProductos (this,true);
        VerificarAdminProductos.setLocationRelativeTo(null);
        VerificarAdminProductos.setVisible(true);  
        this.setVisible(false);
        
        }else{
        JOptionPane.showMessageDialog(this, "Seleccione un Producto");
        }
    }//GEN-LAST:event_jMenu3MouseClicked

    private void TblListaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblListaProductosMouseClicked
        // TODO add your handling code here:
        VistaProducto VistaProducto = new VistaProducto(this, false);
        VistaProducto.setLocationRelativeTo(null);
        VistaProducto.setVisible(true);
    }//GEN-LAST:event_TblListaProductosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaDeProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListaDeProductos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable TblListaProductos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
