/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import logica.conexion;


/**
 *
 * @author boy_d
 */
public final class ListaCompras extends javax.swing.JFrame {
    conexion c = new conexion();
    Connection con = c.getConexion();
    
    String opcion;
    String titulo[] = {"Codigo Cliente", "Nombre", "#Ticket", "SubTotal", "Total", "Ahorro","Fecha"};
    String data[] = new String[8];
    DefaultTableModel modelo;
    /**
     * Creates new form ListaCompras
     */
    public ListaCompras() {
        initComponents();
        consutaProducto();
        buttonGroup1.add(OptCodigoCliente);
        buttonGroup1.add(OptNombreCliente);
        buttonGroup1.add(OptTicket);
        this.setResizable(false);
    }
        void consutaProducto() {
       
        modelo = new DefaultTableModel(null, titulo) {
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }
        };
        String sql="select * from ventas GROUP BY num_ticket  HAVING COUNT(*) > 0";
        try {
            
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                data[0] = rs.getString("codigo_cliente");
                data[1] = rs.getString("nombre_cliente");
                data[2] = rs.getString("num_ticket");
                data[3] = rs.getString("subtotal");
                data[4] = rs.getString("total");
                data[5] = rs.getString("ahorro");
                data[6] = rs.getString("fecha");
                

                modelo.addRow(data);
                TblListaDeCompras.setModel(modelo);

            }

            
        } catch (SQLException ex) {
            System.err.println("Error: " + ex.toString());
        }

    }

    void buscarproducto(String buscar) {
       
        modelo = new DefaultTableModel(null, titulo);
        TblListaDeCompras.setModel(modelo);
        if (OptTicket.isSelected() || OptCodigoCliente.isSelected() || OptNombreCliente.isSelected() ) {
            String sql = "SELECT * from ventas WHERE "+opcion+" like '%"+ buscar +"%' GROUP BY num_ticket HAVING COUNT(*) > 0";
            try {
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                    
                data[0] = rs.getString("codigo_cliente");
                data[1] = rs.getString("nombre_cliente");
                data[2] = rs.getString("num_ticket");
                data[3] = rs.getString("subtotal");
                data[4] = rs.getString("total");
                data[5] = rs.getString("ahorro");
                data[6] = rs.getString("fecha");
                
                    modelo.addRow(data);
                    
                }

               

            } catch (Exception e) {
                System.out.println("Error de consulta de busqueda: " + e.getMessage());
            }
        } else {

            String sql = "SELECT * from ventas WHERE num_ticket like '%"+ TxtCodigoProducto.getText() +"%' GROUP BY num_ticket HAVING COUNT(*) > 0";
            try {
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next()) {
                   
                data[0] = rs.getString("codigo_cliente");
                data[1] = rs.getString("nombre_cliente");
                data[2] = rs.getString("num_ticket");
                data[3] = rs.getString("subtotal");
                data[4] = rs.getString("total");
                data[5] = rs.getString("ahorro");
                data[6] = rs.getString("fecha");
                
                    modelo.addRow(data);
                   
                }

               

            } catch (Exception e) {
                System.out.println("Error de consulta de busqueda: " + e.getMessage());
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblListaDeCompras = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        TxtCodigoProducto = new javax.swing.JTextField();
        OptTicket = new javax.swing.JRadioButton();
        OptCodigoCliente = new javax.swing.JRadioButton();
        OptNombreCliente = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Compras"));
        jPanel1.setToolTipText("");

        TblListaDeCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TblListaDeCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblListaDeComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblListaDeCompras);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Buscar Producto"));

        jLabel6.setText("Codigo:");

        TxtCodigoProducto.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                TxtCodigoProductoCaretUpdate(evt);
            }
        });
        TxtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCodigoProductoActionPerformed(evt);
            }
        });

        OptTicket.setText("Ticket");

        OptCodigoCliente.setText("Codigo Cliente");

        OptNombreCliente.setText("Nombre Cliente");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OptTicket)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OptCodigoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OptNombreCliente)
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OptTicket)
                    .addComponent(OptCodigoCliente)
                    .addComponent(OptNombreCliente))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/regresar-flecha-curva.png"))); // NOI18N
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCodigoProductoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_TxtCodigoProductoCaretUpdate
        // TODO add your handling code here:
        if (OptTicket.isSelected()) {
            opcion = "num_ticket";
        } else {
            if (OptCodigoCliente.isSelected()) {
                opcion = "codigo_cliente";
            } else {
                if (OptNombreCliente.isSelected()) {
                    opcion = "nombre_cliente";
                
                }
            }
        }
        if (TxtCodigoProducto.getText().equals("")) {
            consutaProducto();
        } else {
            buscarproducto(TxtCodigoProducto.getText());

        }
    }//GEN-LAST:event_TxtCodigoProductoCaretUpdate

    private void TxtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCodigoProductoActionPerformed

    private void TblListaDeComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblListaDeComprasMouseClicked
       if(TblListaDeCompras.getSelectedRow()==-1){
       
       }else{
        VistaCompras VistaCompras = new VistaCompras(this, true);
        VistaCompras.setLocationRelativeTo(null);
        VistaCompras.setVisible(true);
       }
    }//GEN-LAST:event_TblListaDeComprasMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        
        Principal ventaPrincipal= new Principal();
        ventaPrincipal.setLocationRelativeTo(null);
        ventaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListaCompras().setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton OptCodigoCliente;
    private javax.swing.JRadioButton OptNombreCliente;
    private javax.swing.JRadioButton OptTicket;
    public static javax.swing.JTable TblListaDeCompras;
    private javax.swing.JTextField TxtCodigoProducto;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
